### ISSUE TITLE
Extra space when formatting date  ${.now?string["yyyy-MM-dd HH:mm:ss"]} got 

### ISSUE THREAD

**Issue by mozhuwanjieDEV** [ranzou06/intellij-javadocs#2]
template content中配置日期格式如：${.now?string["yyyy-MM-dd HH:mm:ss"]} 
得到结果2020 -01-06 16:02:12
年与日之间多了一个空格

![微信截图_20200106161118](https://user-images.githubusercontent.com/9193483/71804776-70e1c900-309f-11ea-8e5c-d0f333a6d4af.png)

![image](https://user-images.githubusercontent.com/9193483/71804785-763f1380-309f-11ea-8e36-1e8997e5b5b0.png)

**Comment by ranzou06** [comment]
I suggest you all change back to the original plugin, since owner are now back to maintaining it.

https://plugins.jetbrains.com/plugin/7157-javadoc
